### ISSUE TITLE
Version of Chart.js

### ISSUE THREAD

**Issue by jyhsu2000** [DraperStudio/Laravel-ChartJS#1]
It works well with Chart.js 1.x.x.
But when I tried with Chart.js 2.x.x,
it shows 
```
Uncaught TypeError: (intermediate value).Line is not a function
```
Do you plan to make it support Chart.js 2.x.x ?

**Comment by DraperStudio** [comment]
Send a PR if you want support for this.

**Comment by jyhsu2000** [comment]
I don't know exact differences between 1.0.2 and newest 2.1.6.
So I'm not sure how to modify to let it compatible with 2.x.x correctly.

**Comment by DraperStudio** [comment]
For 2.0 Support a new Major will be tagged, no need to keep it compatible.

**Comment by jyhsu2000** [comment]
Uhh...what I mean is
I don't know how to modify the code to make it work with 2.0 perfectly.
So I can't send a PR about it.

**Comment by DraperStudio** [comment]
Quick checked and mostly they added and removed methods.

You would need to update these files

https://github.com/DraperStudio/Laravel-ChartJS/blob/master/src/Builder.php
https://github.com/DraperStudio/Laravel-ChartJS/blob/master/resources/views/scripts/extended.blade.php
https://github.com/DraperStudio/Laravel-ChartJS/blob/master/resources/views/scripts/minimal.blade.php

That shouldn't be too hard if you familiar with Chart.js and read some docs for the 2.0 release.
